// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASak3NnRKpT-Mc6D9jzb6gpvZNd1cIUsw',
    appId: '1:355330101237:web:bd0577baca927b47dadabc',
    messagingSenderId: '355330101237',
    projectId: 'new-spotify0101',
    authDomain: 'new-spotify0101.firebaseapp.com',
    storageBucket: 'new-spotify0101.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxWzzdCKyZYDMupcQhhlJtaB_26bSiNEs',
    appId: '1:355330101237:android:fdbd9d64bf17801cdadabc',
    messagingSenderId: '355330101237',
    projectId: 'new-spotify0101',
    storageBucket: 'new-spotify0101.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkes6GOmIy7SSK_yxHqwsyLta6gbkxa1k',
    appId: '1:355330101237:ios:a49ca4cba38d2943dadabc',
    messagingSenderId: '355330101237',
    projectId: 'new-spotify0101',
    storageBucket: 'new-spotify0101.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkes6GOmIy7SSK_yxHqwsyLta6gbkxa1k',
    appId: '1:355330101237:ios:a49ca4cba38d2943dadabc',
    messagingSenderId: '355330101237',
    projectId: 'new-spotify0101',
    storageBucket: 'new-spotify0101.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASak3NnRKpT-Mc6D9jzb6gpvZNd1cIUsw',
    appId: '1:355330101237:web:bba36c4ee9121ca9dadabc',
    messagingSenderId: '355330101237',
    projectId: 'new-spotify0101',
    authDomain: 'new-spotify0101.firebaseapp.com',
    storageBucket: 'new-spotify0101.firebasestorage.app',
  );
}
